- name: Install GPG
  yum: name=gnupg2
  when: ansible_distribution_major_version|int < 6

- name: Upload EPEL GPG key
  copy:
    src: 217521F6.txt
    dest: /tmp/epel_key.txt

- name: Import EPEL GPG key
  rpm_key:
    key: /tmp/epel_key.txt
    validate_certs: "{{epel_validate_certs}}"

- name: Add EPEL repostory
  yum:
    name: "{{epel_rpm_url}}"
    validate_certs: "{{epel_validate_certs}}"
